In [3]:
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
dataset=pd.read_csv("/home/anjana/Downloads/eye.csv")
dataset

     Unnamed: 0    id  laser  eye1  age  type  trt  futime  status  risk
0             1     5      1     1   28     1    1   46.23       0     9
1             2     5      1     1   28     1    0   46.23       0     9
2             3    14      1     2   12     2    1   42.50       0     8
3             4    14      1     2   12     2    0   31.30       1     6
4             5    16      2     2    9     2    1   42.27       0    11
5             6    16      2     2    9     2    0   42.27       0    11
6             7    25      1     1    9     2    1   20.60       0    11
7             8    25      1     1    9     2    0   20.60       0    11
8             9    29      2     1   13     2    1   38.77       0     9
9            10    29      2     1   13     2    0    0.30       1    10
10           11    46      2     2   12     2    1   65.23       0     9
11           12    46      2     2   12     2    0   54.27       1     9
12           13    49      1     2    8     2    1   63.50       0     8
13           14    49      1     2    8     2    0   10.80       1     6
14           15    56      2     2   12     2    1   23.17       0     8
15           16    56      2     2   12     2    0   23.17       0     9
16           17    61      1     2   16     2    1    1.47       0     9
17           18    61      1     2   16     2    0    1.47       0    10
18           19    71      1     2   21     1    1   58.07       0     9
19           20    71      1     2   21     1    0   13.83       1     9
20           21   100      1     1   23     1    1   46.43       1     9
21           22   100      1     1   23     1    0   48.53       0     9
22           23   112      1     2   44     1    1   44.40       0    11
23           24   112      1     2   44     1    0    7.90       1    12
24           25   120      2     1   47     1    1   39.57       0    11
25           26   120      2     1   47     1    0   39.57       0     6
26           27   127      2     2   48     1    1   30.83       1     6
27           28   127      2     2   48     1    0   38.57       1    10
28           29   133      1     2   26     1    1   66.27       0    10
29           30   133      1     2   26     1    0   14.10       1     9
..          ...   ...    ...   ...  ...   ...  ...     ...     ...   ...
364         365  1619      2     1   20     1    1   74.97       0     9
365         366  1619      2     1   20     1    0   61.83       1    12
366         367  1627      2     1   10     2    1    6.57       1    10
367         368  1627      2     1   10     2    0   66.97       0    12
368         369  1636      1     2   16     2    1   38.87       1     6
369         370  1636      1     2   16     2    0   68.30       0     6
370         371  1640      2     1   10     2    1   42.43       1    11
371         372  1640      2     1   10     2    0   46.63       1     9
372         373  1643      2     2   11     2    1   67.07       0     9
373         374  1643      2     2   11     2    0   67.07       0     9
374         375  1649      1     2    1     2    1    2.70       1    10
375         376  1649      1     2    1     2    0    2.70       0    12
376         377  1666      1     1   17     2    1   63.80       0     6
377         378  1666      1     1   17     2    0   63.80       0     8
378         379  1672      1     1    7     2    1   32.63       0     9
379         380  1672      1     1    7     2    0   32.63       0     9
380         381  1683      2     2   29     1    1   62.00       0    10
381         382  1683      2     2   29     1    0   62.00       0     8
382         383  1688      2     1    5     2    1   13.10       1    11
383         384  1688      2     1    5     2    0   54.80       0    10
384         385  1705      2     1    1     2    1    8.00       0     8
385         386  1705      2     1    1     2    0    8.00       0     8
386         387  1717      1     1   22     1    1   51.60       0    12
387         388  1717      1     1   22     1    0   42.33       1    11
388         389  1727      1     2   33     1    1   49.97       0     9
389         390  1727      1     2   33     1    0    2.90       1    10
390         391  1746      1     2    3     2    1   45.90       0    10
391         392  1746      1     2    3     2    0    1.43       1    10
392         393  1749      1     2   32     1    1   41.93       0     9
393         394  1749      1     2   32     1    0   41.93       0     9

[394 rows x 10 columns]

In [4]:
X = dataset.values[:, 0:8]
Y = dataset.values[:,9]

In [5]:
X

array([[1.000e+00, 5.000e+00, 1.000e+00, ..., 1.000e+00, 1.000e+00,
        4.623e+01],
       [2.000e+00, 5.000e+00, 1.000e+00, ..., 1.000e+00, 0.000e+00,
        4.623e+01],
       [3.000e+00, 1.400e+01, 1.000e+00, ..., 2.000e+00, 1.000e+00,
        4.250e+01],
       ...,
       [3.920e+02, 1.746e+03, 1.000e+00, ..., 2.000e+00, 0.000e+00,
        1.430e+00],
       [3.930e+02, 1.749e+03, 1.000e+00, ..., 1.000e+00, 1.000e+00,
        4.193e+01],
       [3.940e+02, 1.749e+03, 1.000e+00, ..., 1.000e+00, 0.000e+00,
        4.193e+01]])

In [6]:
Y

array([ 9.,  9.,  8.,  6., 11., 11., 11., 11.,  9., 10.,  9.,  9.,  8.,
        6.,  8.,  9.,  9., 10.,  9.,  9.,  9.,  9., 11., 12., 11.,  6.,
        6., 10., 10.,  9.,  9., 10., 12.,  9.,  9.,  9.,  6.,  8., 11.,
       12.,  9.,  9.,  9., 12., 10., 10., 12., 11., 12.,  9.,  9., 11.,
        9., 11., 10., 12., 11., 11., 10.,  9.,  9.,  9., 10.,  8.,  9.,
        8.,  9.,  9.,  9., 11., 11., 12., 11.,  8.,  9.,  9.,  9.,  9.,
       10., 12., 10.,  9.,  8., 12., 10., 12., 10., 10., 11., 10., 10.,
       10., 11.,  9.,  9.,  8., 10.,  6.,  9., 12.,  8.,  8.,  9.,  9.,
        9., 10.,  8.,  9.,  9.,  8., 10.,  9., 11., 10., 10., 11.,  8.,
        9., 10.,  8., 10.,  9.,  9., 10.,  9.,  9.,  9., 10., 12., 11.,
        9., 12.,  9.,  8., 12., 10., 10.,  9.,  6.,  9., 12., 10., 11.,
       11.,  9.,  6.,  9., 12., 12., 12.,  9., 12.,  8.,  6., 11., 12.,
       10.,  9.,  8., 10., 11., 11.,  9., 12., 12., 10.,  8.,  8.,  9.,
       11.,  9., 12., 11., 11., 12.,  9.,  9.,  9., 12.,  9.,  8.,  8.,
        9., 11., 11., 11.,  9.,  9., 10., 12., 10., 12., 10., 12., 12.,
       12.,  9., 12.,  9.,  9.,  8.,  6., 11., 10., 10., 10.,  6.,  8.,
        6., 10.,  6.,  8., 10., 10., 12., 11., 10., 12., 12., 12.,  9.,
       10., 12.,  9.,  9.,  9.,  9.,  9.,  9., 10., 12., 10., 11., 11.,
       10.,  9.,  9., 11.,  8.,  9., 12., 12., 11.,  9.,  9.,  9.,  9.,
        9., 11., 11., 10., 11., 10., 11., 10.,  9.,  9., 10., 11., 11.,
       12., 10.,  9.,  9., 10.,  9.,  9., 12., 10.,  9., 12., 11.,  9.,
        9., 11., 12.,  6., 10.,  8.,  8.,  9.,  9.,  9.,  9.,  9.,  9.,
       12., 11.,  9., 10., 10.,  9.,  9.,  9., 10., 10., 11.,  8., 10.,
        9.,  9.,  6., 11.,  9.,  9., 11., 10., 10., 10.,  9.,  6.,  6.,
       11., 11., 11., 11., 10.,  9.,  8., 12., 11., 11., 11., 11.,  9.,
       10.,  8., 12.,  9.,  9.,  9.,  8., 11.,  9., 11.,  9.,  9.,  9.,
       12., 11., 10.,  9.,  9.,  9., 12., 10., 12., 11., 10.,  9.,  9.,
        9.,  9.,  9.,  9., 10.,  8., 12.,  9., 10., 10., 10.,  9.,  9.,
        9., 12., 10., 12.,  6.,  6., 11.,  9.,  9.,  9., 10., 12.,  6.,
        8.,  9.,  9., 10.,  8., 11., 10.,  8.,  8., 12., 11.,  9., 10.,
       10., 10.,  9.,  9.])

In [7]:
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size = 0.3, random_state = 100)

In [9]:
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                               max_depth=3, min_samples_leaf=5)
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [21]:
y_pred=clf_gini.predict(X_test)
y_pred

array([10.,  9.,  9., 10., 10.,  8.,  8.,  8.,  9., 12.,  9., 10.,  9.,
        9.,  9., 10., 10.,  9.,  9., 10., 10.,  8.,  9.,  9., 10.,  9.,
        9., 10.,  9.,  9.,  9.,  9., 10., 10., 10.,  9., 10., 10.,  9.,
       10.,  9.,  9.,  9.,  9.,  8., 10., 10., 10.,  9.,  9.,  9.,  9.,
       10.,  9.,  9., 12.,  8.,  9., 10., 12.,  9., 12.,  9.,  9.,  9.,
        9., 10., 10.,  9., 10.,  9.,  9.,  9.,  9.,  9., 10.,  9., 10.,
        6.,  9.,  8.,  9.,  9., 10.,  9., 10., 10., 10.,  9.,  9.,  9.,
        9.,  9.,  9.,  9.,  9., 10.,  9.,  8.,  9., 10., 10.,  8., 10.,
        8., 10.,  9., 10., 10.,  9., 10.,  9., 10.,  9.,  9.,  8.,  9.,
        9., 12.])

In [22]:
y_pred

array([10.,  9.,  9., 10., 10.,  8.,  8.,  8.,  9., 12.,  9., 10.,  9.,
        9.,  9., 10., 10.,  9.,  9., 10., 10.,  8.,  9.,  9., 10.,  9.,
        9., 10.,  9.,  9.,  9.,  9., 10., 10., 10.,  9., 10., 10.,  9.,
       10.,  9.,  9.,  9.,  9.,  8., 10., 10., 10.,  9.,  9.,  9.,  9.,
       10.,  9.,  9., 12.,  8.,  9., 10., 12.,  9., 12.,  9.,  9.,  9.,
        9., 10., 10.,  9., 10.,  9.,  9.,  9.,  9.,  9., 10.,  9., 10.,
        6.,  9.,  8.,  9.,  9., 10.,  9., 10., 10., 10.,  9.,  9.,  9.,
        9.,  9.,  9.,  9.,  9., 10.,  9.,  8.,  9., 10., 10.,  8., 10.,
        8., 10.,  9., 10., 10.,  9., 10.,  9., 10.,  9.,  9.,  8.,  9.,
        9., 12.])

In [23]:
print("Accuracy of gini is ", accuracy_score(y_test,y_pred)*100  )

Accuracy of gini is  35.294117647058826

In [25]:
with open("decision_classifier.txt", "w") as f:
    f = tree.export_graphviz(clf_gini, out_file=f)